using System.Text.Json.Serialization;

namespace Yarpa.Contracts;

/// <summary>
/// The single JSON model the Agent sends to the API. Metadata plus a map of
/// sections, each with its own status. This type is the source of truth for the
/// JSON contract shared by Agent and API. See docs/data-model-and-api.md.
/// </summary>
public sealed class DiagnosticsSnapshot
{
    /// <summary>Current JSON schema version. Bumped (major) on a breaking change.</summary>
    public const string CurrentSchemaVersion = "1.0";

    /// <summary>Idempotency key generated by the Agent for this snapshot.</summary>
    [JsonPropertyName("snapshotId")]
    public Guid SnapshotId { get; init; }

    [JsonPropertyName("schemaVersion")]
    public string SchemaVersion { get; init; } = CurrentSchemaVersion;

    [JsonPropertyName("agentVersion")]
    public string AgentVersion { get; init; } = string.Empty;

    /// <summary>Stable machine fingerprint derived by the Agent.</summary>
    [JsonPropertyName("machineId")]
    public string MachineId { get; init; } = string.Empty;

    /// <summary>
    /// Optional site/customer code entered by the technician at install time (e.g. CRM customer ID).
    /// Helps identify which pharmacy a machine belongs to when many sites share one API key.
    /// </summary>
    [JsonPropertyName("siteCustomerCode")]
    public string? SiteCustomerCode { get; init; }

    [JsonPropertyName("collectedAtUtc")]
    public DateTimeOffset CollectedAtUtc { get; init; }

    /// <summary>Map of section name (e.g. "os", "disks") to its envelope.</summary>
    [JsonPropertyName("sections")]
    public Dictionary<string, SnapshotSection> Sections { get; init; } = new();
}
