// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yarpa.Api.Data;

#nullable disable

namespace Yarpa.Api.Data.Migrations
{
    [DbContext(typeof(YarpaDbContext))]
    partial class YarpaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yarpa.Api.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KeyHash");

                    b.ToTable("ApiKeys", (string)null);

                    b.HasData(
                        new
                        {
                            ApiKeyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            KeyHash = "6ae2432f025fb1ccc63518e80b02ef5ff04e1b19a541cbfa4024ebeff47bdd19"
                        });
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Yarpa Dev"
                        });
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.MachineEntity", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MachineId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.SnapshotEntity", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("MinFreeDiskPercent")
                        .HasColumnType("float");

                    b.Property<string>("OsBuild")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OsCaption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("RamTotalMb")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("SqlInstalled")
                        .HasColumnType("bit");

                    b.Property<string>("YarpaVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SnapshotId");

                    b.HasIndex("MachineId", "CollectedAtUtc");

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("Yarpa.Api.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("ApiKeys")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.MachineEntity", b =>
                {
                    b.HasOne("Yarpa.Api.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("Machines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.SnapshotEntity", b =>
                {
                    b.HasOne("Yarpa.Api.Data.Entities.MachineEntity", "Machine")
                        .WithMany("Snapshots")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.CustomerEntity", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Machines");
                });

            modelBuilder.Entity("Yarpa.Api.Data.Entities.MachineEntity", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
