namespace Yarpa.Api.Data.Entities;

/// <summary>
/// An immutable, append-only record of one diagnostic collection run.
/// The full JSON payload is preserved in RawJson. Frequently queried fields
/// are also stored as typed columns to allow fast filtering without JSON parsing.
/// </summary>
public sealed class SnapshotEntity
{
    /// <summary>Primary key — the GUID generated by the Agent (idempotency key).</summary>
    public Guid SnapshotId { get; set; }

    public string MachineId { get; set; } = string.Empty;

    /// <summary>Timestamp from the Agent when collection started.</summary>
    public DateTime CollectedAtUtc { get; set; }

    /// <summary>Timestamp when the API received and stored the snapshot.</summary>
    public DateTime ReceivedAtUtc { get; set; }

    public string AgentVersion { get; set; } = string.Empty;

    public string SchemaVersion { get; set; } = string.Empty;

    /// <summary>Complete JSON body as received from the Agent.</summary>
    public string RawJson { get; set; } = string.Empty;

    // ── Decoded columns for fast queries ─────────────────────────────────────

    /// <summary>Windows caption, e.g. "Windows 11 Pro".</summary>
    public string? OsCaption { get; set; }

    /// <summary>Windows build number, e.g. "22631".</summary>
    public string? OsBuild { get; set; }

    /// <summary>Total installed RAM in megabytes.</summary>
    public long? RamTotalMb { get; set; }

    /// <summary>Minimum free-space percentage across all disks (for quick disk-full alert query).</summary>
    public double? MinFreeDiskPercent { get; set; }

    /// <summary>Yarpa ERP version string, when present in the yarpaVersion section.</summary>
    public string? YarpaVersion { get; set; }

    /// <summary>Whether SQL Server is installed according to the sqlServer section.</summary>
    public bool? SqlInstalled { get; set; }

    // Navigation
    public MachineEntity Machine { get; set; } = null!;
    public ICollection<ChangeEntity> Changes { get; set; } = new List<ChangeEntity>();
}
